name = "fangdash"
main = ".open-next/worker.js"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
ENVIRONMENT = "production"
