import js from "@eslint/js";
import nextPlugin from "@next/eslint-plugin-next";
import prettier from "eslint-config-prettier";
import unusedImports from "eslint-plugin-unused-imports";
import tseslint from "typescript-eslint";

export default tseslint.config(
	// Global ignores
	{
		ignores: [
			"**/node_modules/**",
			"**/dist/**",
			"**/.next/**",
			"**/.turbo/**",
			"**/.open-next/**",
			"**/.wrangler/**",
			"**/.partykit/**",
			"**/.localflare/**",
			"**/.source/**",
			"**/out/**",
			"**/public/sw.js",
			"**/public/workbox-*.js",
			"**/scripts/**",
			"**/.localflare/**",
		],
	},

	// Base configs
	js.configs.recommended,
	...tseslint.configs.recommended,

	// Unused imports plugin
	{
		plugins: {
			"unused-imports": unusedImports,
		},
		rules: {
			"no-unused-vars": "off",
			"@typescript-eslint/no-unused-vars": "off",
			"unused-imports/no-unused-imports": "error",
			"unused-imports/no-unused-vars": [
				"error",
				{
					vars: "all",
					varsIgnorePattern: "^_",
					args: "after-used",
					argsIgnorePattern: "^_",
				},
			],
		},
	},

	// General rules
	{
		rules: {
			"no-param-reassign": "error",
			"@typescript-eslint/no-non-null-assertion": "warn",
			"@typescript-eslint/no-explicit-any": "warn",
			"@typescript-eslint/no-empty-object-type": "off",
			"@typescript-eslint/no-require-imports": "off",
		},
	},

	// Node.js globals for config files and mjs scripts
	{
		files: ["**/*.config.{ts,mjs,js}", "**/*.mjs"],
		languageOptions: {
			globals: {
				process: "readonly",
				console: "readonly",
				Buffer: "readonly",
				__dirname: "readonly",
				__filename: "readonly",
				module: "readonly",
				require: "readonly",
			},
		},
	},

	// Next.js plugin for web and docs apps
	{
		files: ["apps/web/**/*.{ts,tsx,js,jsx}", "apps/docs/**/*.{ts,tsx,js,jsx}"],
		plugins: {
			"@next/next": nextPlugin,
		},
		rules: {
			...nextPlugin.configs.recommended.rules,
			...nextPlugin.configs["core-web-vitals"].rules,
			"@next/next/no-img-element": "off",
			"@next/next/no-html-link-for-pages": "off",
		},
	},

	// Allow default exports in framework files
	{
		files: [
			"**/app/**/{page,layout,loading,error,not-found,sitemap,robots,manifest,route}.{ts,tsx}",
			"**/*.config.{ts,mjs,js}",
			"**/next.config.{ts,mjs,js}",
			"**/open-next.config.ts",
			"**/postcss.config.mjs",
			"**/vitest.config.ts",
			"**/vitest.workspace.ts",
			"**/drizzle.config.ts",
			"**/source.config.ts",
			"apps/party/src/**/*.ts",
			"apps/api/src/index.ts",
		],
		rules: {
			// These files require default exports by convention
		},
	},

	// next-env.d.ts is auto-generated by Next.js and uses triple-slash references
	{
		files: ["apps/web/next-env.d.ts"],
		rules: {
			"@typescript-eslint/triple-slash-reference": "off",
		},
	},

	// Prettier must be last
	prettier,
);
