name = "fangdash-api"
main = "src/index.ts"
compatibility_date = "2025-02-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fangdash-db"
database_id = "b9de4b53-55fd-4490-b4d1-2534da296b0e"
migrations_dir = "drizzle"

[vars]
ENVIRONMENT = "development"

[env.production]
name = "fangdash-api"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "fangdash-db"
database_id = "b9de4b53-55fd-4490-b4d1-2534da296b0e"
migrations_dir = "drizzle"
